# rigetti-takehome

was facing some errors in connecting the websocket endpoint -> resolved by adding debug statemtns and checking logs
-> realised i was having issues with multiple ids

- realised websocket wasn't receiveing the connection
- didnt have some dependeices installed
"timestamp": int(time.time()) was too similar so when creating had duplicate keys

